"use strict";(()=>{var e={};e.id=228,e.ids=[228],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},1282:e=>{e.exports=require("child_process")},4770:e=>{e.exports=require("crypto")},665:e=>{e.exports=require("dns")},7702:e=>{e.exports=require("events")},2048:e=>{e.exports=require("fs")},2615:e=>{e.exports=require("http")},5240:e=>{e.exports=require("https")},8216:e=>{e.exports=require("net")},9801:e=>{e.exports=require("os")},5315:e=>{e.exports=require("path")},6162:e=>{e.exports=require("stream")},2452:e=>{e.exports=require("tls")},7360:e=>{e.exports=require("url")},1764:e=>{e.exports=require("util")},1568:e=>{e.exports=require("zlib")},2124:(e,r,s)=>{s.r(r),s.d(r,{originalPathname:()=>g,patchFetch:()=>x,requestAsyncStorage:()=>l,routeModule:()=>c,serverHooks:()=>m,staticGenerationAsyncStorage:()=>d});var o={};s.r(o),s.d(o,{POST:()=>u});var t=s(9303),n=s(8716),a=s(670),i=s(7070);let p=s(5245).createTransport({service:"gmail",auth:{user:process.env.EMAIL_USER,pass:process.env.EMAIL_APP_PASSWORD}});async function u(e){let r=await e.json(),{firstName:s,lastName:o,email:t,message:n}=r,a=s&&o?`${s} ${o}`:t;try{if(console.log("Request Data:",r),console.log("Name:",a),console.log("Email:",t),console.log("Message:",n),!s||!o||!t||!n)return i.NextResponse.json({error:"Missing required fields: name, email, and message are required."},{status:400});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(t))return i.NextResponse.json({error:"Invalid email address format."},{status:400});let e={from:process.env.EMAIL_USER,to:t,subject:"Thank You for Your Purchase!",html:`
        <p>Dear ${a},</p>
        <p>Thank you for your purchase! Your order confirmation is below:</p>
        <p>Message: ${n}</p> <p>Best regards,</p>
        <p>Your Company Name</p>
      `},u={from:process.env.EMAIL_USER,to:process.env.EMAIL_USER,subject:"New Beat Purchase",html:`
        <p>A new beat has been purchased:</p>
        <p>Customer Name: ${a}</p>
        <p>Customer Email: ${t}</p> 
        <p>Message: ${n}</p>
      `};return await Promise.all([p.sendMail(e),p.sendMail(u)]),i.NextResponse.json({success:!0})}catch(e){if(console.error("SMTP Debug:",{user:process.env.EMAIL_USER,authMethod:"App Password"}),e instanceof Error)return console.error("Full error details:",{message:e.message}),i.NextResponse.json({error:"Failed to send email.",details:{message:e.message}},{status:500});return console.error("An unknown error occurred:",e),i.NextResponse.json({error:"An unknown error occurred.",details:{code:e.code,response:e.response}},{status:500})}}p.verify(function(e,r){e?console.error("SMTP connection error:",e):console.log("SMTP server is ready to take our messages")});let c=new t.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/api/email/confirmation/route",pathname:"/api/email/confirmation",filename:"route",bundlePath:"app/api/email/confirmation/route"},resolvedPagePath:"C:\\Users\\kaleb\\Documents\\companydev\\Genesis Reborn Productions\\Websitedev\\genesisrebornproductions-app-genesisrebornproductions\\genesisrebornproductions-app-genesisrebornproductions\\src\\app\\api\\email\\confirmation\\route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:l,staticGenerationAsyncStorage:d,serverHooks:m}=c,g="/api/email/confirmation/route";function x(){return(0,a.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:d})}}};var r=require("../../../../webpack-runtime.js");r.C(e);var s=e=>r(r.s=e),o=r.X(0,[948,972,245],()=>s(2124));module.exports=o})();